github: [metadata]
repository: smallAreaHealthStatisticsUnit/rapidInquiryFacility
theme: jekyll-theme-cayman
encoding: UTF-8
kramdown:
   input: GFM
   hard_wrap: false
future: true
jailed: false
#theme: jekyll-theme-primer
gfm_quirks: paragraph_end

# ---------------------------------------------------------------------------------------
# 
# There is some confusion about what the baseurl value should be. The one specifying 
# the project name seems like it should work for GitHub Pages, and it can easily be 
# overridden for local Jekyll runs if necessary, as follows:
#
#   bundle exec jekyll serve --baseurl ''
#
baseurl: /rapidInquiryFacility
# baseurl: ""
# ---------------------------------------------------------------------------------------
